## Data Preprocessing

Importing Lib 

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing Dataset

In [20]:
ds = pd.read_csv('Data.csv')
x = ds.iloc[:,:-1].values
y = ds.iloc[:,-1].values

In [21]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [22]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking Care of Missing data
 

In [26]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values=np.nan, strategy='mean')
si.fit(x[:,1:3])
x[:,1:3] = si.transform(x[:,1:3])


In [27]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Categorical Encoding

In [28]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encode', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [29]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Label Encoder

In [30]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [31]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


Spliting the dataset into training set and test set

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [33]:
print(x_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [34]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 50.0 83000.0]]


In [35]:
print(y_train)

[1 1 1 0 1 0 0 1]


In [36]:
print(y_test)

[0 0]


Standardzation

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_train[:,3:])

TypeError: float() argument must be a string or a real number, not 'StandardScaler'

In [38]:
print(x_train)

[[0.0 1.0 0.0 StandardScaler() StandardScaler()]
 [1.0 0.0 0.0 StandardScaler() StandardScaler()]
 [0.0 0.0 1.0 StandardScaler() StandardScaler()]
 [0.0 0.0 1.0 StandardScaler() StandardScaler()]
 [1.0 0.0 0.0 StandardScaler() StandardScaler()]
 [0.0 0.0 1.0 StandardScaler() StandardScaler()]
 [1.0 0.0 0.0 StandardScaler() StandardScaler()]
 [1.0 0.0 0.0 StandardScaler() StandardScaler()]]
